repos:
  - repo: local
    hooks:
      - id: sqlfluff-project-lint
        name: sqlfluff project lint
        entry: scripts/lint_sql_projects.sh
        language: system
        files: ^projects/.+[.]sql$
