name: jaffle_shared
version: "0.1.0"
config-version: 2

profile: jaffle_corp
require-dbt-version: ">=1.8.0,<2.0.0"

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

target-path: target
clean-targets:
  - target
  - dbt_packages
