select
    {{ jaffle_shared.stable_hash(['support_ticket_id']) }} as support_ticket_key,
    support_ticket_id,
    customer_id,
    order_id,
    store_id,
    opened_at_utc,
    opened_date_utc,
    first_response_at_utc,
    resolved_at_utc,
    normalized_issue_type,
    raw_issue_type,
    ticket_status,
    resolution_type,
    satisfaction_score,
    concession_minor,
    concession_major,
    currency,
    first_response_minutes,
    resolution_minutes,
    first_response_sla_status,
    resolution_sla_status,
    order_status,
    channel,
    order_total_usd,
    net_revenue_usd,
    estimated_gross_margin_usd,
    refund_event_count,
    has_failed_payment,
    revenue_quality_status,
    first_response_sla_status = 'within_target' as met_first_response_sla,
    resolution_sla_status = 'within_target' as met_resolution_sla,
    updated_at_utc
from {{ ref('int_ticket_sla_events') }}
