select
    store_day_capacity_plan_key,
    calendar_id,
    store_id,
    calendar_date_utc,
    scenario_name,
    day_type,
    expected_open_minutes,
    local_holiday_name,
    menu_focus,
    forecasted_order_count,
    actual_order_count,
    absolute_forecast_error_orders,
    inside_interval_hour_count,
    forecast_hour_count,
    operations_order_count,
    ready_target_rate,
    quality_exception_count,
    incident_count,
    net_revenue_usd,
    estimated_gross_margin_usd,
    {{ shared.safe_divide('forecasted_order_count', 'expected_open_minutes / 60.0') }} as forecasted_orders_per_open_hour,
    {{ shared.safe_divide('actual_order_count', 'expected_open_minutes / 60.0') }} as actual_orders_per_open_hour,
    {{ shared.safe_divide('inside_interval_hour_count', 'forecast_hour_count') }} as prediction_interval_hit_rate
from {{ ref('int_store_day_plan_inputs') }}
